### PR TITLE
Fix synchronizer is_playing return value

### PR DESCRIPTION
**Pull request by RichardAntalik**
Fix core audio synchronizer returning value different than default
synchronizer when not playng.

This causes issues in Blender code, see https://projects.blender.org/blender/blender/issues/107726#issuecomment-991514

### CODE REVIEW

**Comment by RichardAntalik** [comment]
Oh no, I have pushed past changes to master on my remote :(
Will try to fix

**Comment by neXyon** [comment]
I guess you didn't? The last commit is what you want, I assume? It looks weird, shouldn't a cast from `bool` to `int` result in 0 for `false` and 1 for `true`? What do you get?

**Comment by neXyon** [comment]
I'm trying to figure out what you want to do here. -1 is not the result it should produce, it should be 0 like on the other actual implementations (of which there is only jack, next to coreaudio). -1 is used for error cases, e.g., like there being no actual synchronizer available (like what the default synchronizer gives you). Coreaudio does have a synchronizer so it should actually return 0 and 1. What's the actual issue you are trying to solve?

**Comment by RichardAntalik** [comment]
Yes, it's last commit I wanted to propose. The issue I want to solve is mentioned in this PR description. If 1 or 0 is expected return value, then this PR could be closed, and issue would be in Blender code. I guess, I don't quite understand the purpose of the synchronizer or why it is needed for coreaudio, when on windows it effectively only implements seeking.

**Comment by neXyon** [comment]
Ah yeah, I overlooked it, my mistake. Sorry! I have responded there and will close this here.

**Pull request closed without merging**
